# Generated by Django 6.0 on 2025-12-09 22:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced')], max_length=20)),
                ('citizenship', models.CharField(default='Filipino', max_length=50)),
                ('house_number', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=50)),
                ('barangay', models.CharField(default='Your Barangay Name', max_length=100)),
                ('city_municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('educational_attainment', models.CharField(choices=[('no_formal', 'No Formal Education'), ('elementary', 'Elementary'), ('high_school', 'High School'), ('vocational', 'Vocational'), ('college', 'College'), ('post_graduate', 'Post Graduate')], max_length=20)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired'), ('self_employed', 'Self Employed'), ('ofw', 'OFW')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('spouse_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_name', models.CharField(max_length=150)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('philhealth_number', models.CharField(blank=True, max_length=20)),
                ('sss_gsis_number', models.CharField(blank=True, max_length=20)),
                ('tin_number', models.CharField(blank=True, max_length=20)),
                ('voters_id', models.CharField(blank=True, max_length=20)),
                ('is_pwd', models.BooleanField(default=False, verbose_name='Person with Disability')),
                ('pwd_type', models.CharField(blank=True, max_length=100, verbose_name='PWD Type')),
                ('is_senior_citizen', models.BooleanField(default=False)),
                ('is_solo_parent', models.BooleanField(default=False)),
                ('is_indigenous', models.BooleanField(default=False, verbose_name='Indigenous Person')),
                ('is_4ps_beneficiary', models.BooleanField(default=False, verbose_name='4Ps Beneficiary')),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_number', models.CharField(max_length=20, unique=True)),
                ('total_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('house_ownership', models.CharField(choices=[('owned', 'Owned'), ('rented', 'Rented'), ('shared', 'Shared'), ('caretaker', 'Caretaker')], default='owned', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headed_household', to='residents.resident')),
                ('members', models.ManyToManyField(blank=True, related_name='households', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Household',
                'verbose_name_plural': 'Households',
                'ordering': ['household_number'],
            },
        ),
    ]
