# Generated by Django 6.0 on 2025-12-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='precinct_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
